### ISSUE TITLE
Paid developer account not necessary + the ubuntu server iso you have linked in readme.md missing package

### ISSUE THREAD

**Issue by ZoeyCluff** [diddledani/macOS-Linux-VM-with-Rosetta#1]
just tested this out on my free developer account on Ventura (using the dev beta profile off a website).

xcode changes were basically sign to run locally and use my developer stuff in xcode

Works great and is stupid fast! 

the ubuntu server iso is missing the update-binfmts command, but a simple apt install binfmt-support added it.

![CleanShot 2022-06-18 at 12 55 13](https://user-images.githubusercontent.com/2716914/174450767-4329f14a-6b8b-4e8d-96f6-1150e2c7a076.png)

Also, installing ubuntu-desktop^ does give a working desktop

![image](https://user-images.githubusercontent.com/2716914/174451380-0f185375-fee1-48de-b0bf-6785581964ea.png)

thank you for this!

**Comment by diddledani** [comment]
Thanks for the reminder about `binfmt-support` that I'd forgotten to add to the README, and to add them instructions for installing the desktop environment. I've added both to the README now.

Thank you also for letting me know that a paid developer account isn't required - I've amended the README to match your experience here.
