### ISSUE TITLE
Guest did stop virtual machine

### ISSUE THREAD

**Issue by kvz** [diddledani/macOS-Linux-VM-with-Rosetta#19]
Hi there,

I have downloaded the latest:

- macOS 13 beta
- RosettaVM
- ubuntu-22.04.1-live-server-amd64.iso

I can start RosettaVM and get a black screen and a file open dialog. When I click to load the Ubuntu iso, RosettaVM stops.

Now when I start it again, it insta-stops.

To get more details, I tried running from the terminal, and get:

```bash
❯ /Applications/RosettaVM.app/Contents/MacOS/RosettaVM
Virtual machine successfully started.
Guest did stop virtual machine.
```

Any idea would be appreciated :)

**Comment by kvz** [comment]
Hi 👋 :) 

running amd64 software on arm inside a VM is quite valuable to our company and si I was wondering if we could sponsor you for assistance with this?

**Comment by ryansch** [comment]
@kvz Did you try to install the amd64 version of ubuntu? That won't work.

**Comment by kvz** [comment]
I was about to write, certainly not I am running arm on arm, then i checked my original post and may have done something very silly, will doublecheck and be back to report if it was indeed that mistake 👌

**Comment by kvz** [comment]
Okay yes my mistake, i used an AMD64 image versus an ARM one. 

One thing, i could not select a different image anymore after this mistake until I ran

```bash
sudo rm -rf /Applications/RosettaVM.app ~/Library/Containers/com.diddledani.RosettaVM
```

and then reinstalled and tried again. 

Otherwise just running the app would immediately exit it on: 

```bash
❯ /Applications/RosettaVM.app/Contents/MacOS/RosettaVM
Virtual machine successfully started.
Guest did stop virtual machine.
```

.. without the possibility of selecting a different image
