### ISSUE TITLE
Where is the VM Hard Drive or .HDD or .img or .vhdx install directory of this located?

### ISSUE THREAD

**Issue by bdwandry** [diddledani/macOS-Linux-VM-with-Rosetta#24]
Hi I know this is not really any issue topic, 

but there is very limited documentation. 
But where is the download location for the virtual hdd of this vm?

I have found a connected folder in ~/library/application scripts/com.diddledani.RosettaVM.
But the vm virt hdd is not located within'

**Comment by bdwandry** [comment]
Figured it out

**Comment by dkwdaft** [comment]
> Figured it out

I have the same question, what is the answer please?

**Comment by diddledani** [comment]
Hi,

The disk image is located at `Library/Containers/com.diddledani.RosettaVM/Data/RosettaVM.bundle/Disk.img`. The easiest way to reset the image is to delete the whole folder at `Library/Containers/com.diddledani.RosettaVM/Data/RosettaVM.bundle`.
